# Generated by Django 5.2.7 on 2025-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('preference', models.CharField(choices=[('hospitality', 'Hospitality'), ('commerce', 'Commerce'), ('pharmacy', 'Pharmacy'), ('agriculture', 'Agriculture'), ('tourism', 'Tourism'), ('technical_services', 'Technical Services'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
