# Generated by Django 5.2.7 on 2025-10-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_create_customers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_manage_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_manage_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
