# Generated by Django 5.2.7 on 2025-10-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_membership_can_create_customers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['organization', 'role']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='preference',
            field=models.CharField(choices=[('hospitality', 'Hospitality'), ('commerce', 'Commerce'), ('pharmacy', 'Pharmacy / Health'), ('agriculture', 'Agriculture'), ('tourism', 'Tourism'), ('technical_services', 'Technical Services'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'organization')},
        ),
    ]
