# Generated by Django 5.2.7 on 2025-10-12 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_membership_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hospitality', 'Hospitality'), ('commerce', 'Commerce'), ('pharmacy', 'Pharmacy / Health'), ('agriculture', 'Agriculture'), ('tourism', 'Tourism'), ('technical_services', 'Technical Services'), ('other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
