# Generated by Django 5.2.7 on 2025-10-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
